#!/bin/bash

# serverextensions
jupyter serverextension enable --sys-prefix --py nbserverproxy
jupyter serverextension enable --sys-prefix --py nbgitpuller

# Back to home
cd ~

# install the panel server extension so that
# panel launches at startup
mv binder/panelserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# enable panel extension
jupyter serverextension enable --sys-prefix panelserverextension

